image:
  name: "golang:1.18.2-buster"
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
stages:
  - tests
  - build
  - upload


variables:
  PACKAGE_VERSION: "0.1.0"
  DARWIN_AMD64_BINARY: "awsrouters"
  LINUX_AMD64_BINARY: "awsrouters-linux"
  #WINDOWS_BINARY: 
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/2228/packages/go/${PACKAGE_VERSION}"
unittest:
  stage: tests
  script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task testd

integrationtest:
  stage: tests
  script:
    - go install gitlab.presidio.com/rgomez/aws-router
    - mkdir csv
    - aws-router
    - mkdir excel
    - aws-router excel
    - touch .go-aws-routing.yaml
    - >
      echo "db_Name: testing-db123" > .go-aws-routing.yaml
    - aws-router sync
  tags:
    - aws
  artifacts:
    paths: 
      - csv
      - excel

build:
  stage: build
  script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task build
    - task buildlinux
    - task buildwindows
  artifacts:
    paths:
      - "${DARWIN_AMD64_BINARY}"
      - "awsrouters.exe"
      - "${LINUX_AMD64_BINARY}"

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${DARWIN_AMD64_BINARY} "${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${LINUX_AMD64_BINARY} "${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}"
# release:
#   stage: release
#   script:
#     - echo 'running release_job'
#     - echo 'Previous Job ID is printed below'
#     - echo $GE_JOB_ID
#   needs:
#     - build
#       artifacts: true
#   release:
#     tag_name: "$CI_COMMIT_SHORT_SHA"
#     description: "Release $CI_COMMIT_SHORT_SHA"
#     name: "Release $CI_COMMIT_SHORT_SHA"
#     assets:
#       links:
#         - name: "Linux Release"
#           url: "https://gitlab.presidio.com/rgomez/aws-router/-/jobs/${GE_JOB_ID}/artifacts/raw/awsrouters-linux"