image:
  name: "golang:1.18.2-buster"
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
stages:
  - tests
  - build
  - release

unittest:
  stage: tests
  script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task testd

integrationtest:
  stage: tests
  script:
    - go install gitlab.presidio.com/rgomez/aws-router
    - mkdir csv
    - aws-router
    - mkdir excel
    - aws-router excel
    - touch .go-aws-routing.yaml
    - >
      echo "db_Name: testing-db123" > .go-aws-routing.yaml
    - aws-router sync
  tags:
    - aws
  artifacts:
    paths: 
      - csv
      - excel

build:
  stage: build
  script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task build
    - task buildlinux
    - task buildwindows
  artifacts:
    paths:
      - "awsrouters"
      - "awsrouters.exe"
      - "awsrouters-linux"

release:
  stage: release
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
  needs:
    - build
      artifacts: true
  release:
    tag_name: "$CI_COMMIT_SHORT_SHA"
    description: "Release $CI_COMMIT_SHORT_SHA"
    name: "Release $CI_COMMIT_SHORT_SHA"
    assets:
      links:
        - name: "Linux Release"
          url: "https://gitlab.presidio.com/rgomez/aws-router/-/jobs/${GE_JOB_ID}/artifacts/raw/awsrouters-linux"