# image:
#   name: "golang:1.18.2-buster"
#   entrypoint:
#     - "/usr/bin/env"
#     - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
stages:
  - tests
  - build


variables:
  PACKAGE_VERSION: "0.1.0"
  DARWIN_AMD64_BINARY: "awsrouters"
  LINUX_AMD64_BINARY: "awsrouters-linux"
  WINDOWS_BINARY: "awsrouters.exe"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/2228/packages/go/${PACKAGE_VERSION}"

unittest:
  stage: tests
  script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task testd

integrationtest:
  stage: tests
  script:
    - go install gitlab.presidio.com/rgomez/aws-router
    - mkdir csv
    - aws-router
    - mkdir excel
    - aws-router excel
    - touch .go-aws-routing.yaml
    - >
      echo "db_Name: testing-db123" > .go-aws-routing.yaml
    - aws-router sync
  tags:
    - aws
  artifacts:
    paths: 
      - csv
      - excel

build:
  stage: build
  script:
    - echo "${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}"
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task build
    - task buildlinux
    - task buildwindows
  artifacts:
    paths:
      - "awsrouters"
      - "awsrouters.exe"
      - "awsrouters-linux"
