version: "3"

tasks:
  test:
    cmds:
      - go test -v ./...
  race:
    cmds:
      - go test -race -v ./...
  build:
    cmds:
      - GOOS=darwin go build -o awsrouters *.go
  buildwindows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o awsrouters.exe *.go
  buildlinux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o awsrouters-linux
  buildall:
    deps:
      - build
      - buildwindows
  cleancsv:
    cmds:
      - rm -f csv/*.csv
      - rm -f excel/*.xlsx
