version: "3"

tasks:
  test:
    cmds:
      - go test -cover ./...
  testd:
    cmds:
      - go test -cover -v ./...
  race:
    cmds:
      - go test -race -v ./...
  build:
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -o ./bin/mac_arm64/awsrouters *.go
  buildMacIntel:
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o ./bin/mac_amd64/awsrouters *.go
  buildwindows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o ./bin/windows_amd64/awsrouters.exe *.go
  buildlinux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ./bin/linux_amd64/awsrouters *.go
  buildall:
    deps:
      - build
      - buildwindows
      - buildlinux
  docs:
    cmds:
      - echo "Open the browser and navigate to http://localhost:6060/docs"
      - echo "To get all methods, fields and types regardless if they are exported or not, use '?m=all' at the end of the URL"
      - godoc -http=:6060
  cleanexports:
    cmds:
      - rm -f csv/*.csv
      - rm -f excel/*.xlsx
