name: UnitTests

on:
  push:
    branches: ["main", "features/*", "issues/*"]
  pull_request:
    branches: ["main", "features/*", "issues/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18.2-buster
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Path info
        run: pwd
      - name: Files info
        run: ls -la
      - name: Unit Tests
        run: go test -cover -v ./...
