name: IntegrationTest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted
    container: golang:1.18.2-buster
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Path info
        run: pwd
      - name: Files info
        run: ls -la
      - name: Build for the current platform
        run: go build -o awsrouters *.go
      - name: Change permissions
        run: chmod +x awsrouters
      - name: Running the root command
        run: ./awsrouters
        env:
          AWS_REGION: us-east-1
      - name: Running the root command
        run: ./awsrouters
        env:
          AWS_REGION: us-east-1
      - name: Running a db sync command 
        env:
          AWS_REGION: us-east-1
        run: |
          touch .go-aws-routing.yaml
          echo "db_Name: testing-db123" > .go-aws-routing.yaml
          aws-router sync
      - name: Running a path sync command 
        env:
          AWS_REGION: us-east-1
        run: aws-router path 10.0.1.1 10.0.2.1

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.18

  #     - name: Set up task
  #       run: go install github.com/go-task/task/v3/cmd/task@latest

  #     - name: Test
  #       uses: golang:1.18.2-buster
  #       run: go test -v ./...

  #     - name: Build
  #       run: task buildall
